# IO Error handling
f=open("test.py","r")

